/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace EvidenceRegistry {
      
    export type EvidenceAnchorStruct = {caseIdHash: BytesLike, documentIdHash: BytesLike, contentHash: BytesLike, version: BigNumberish, anchoredAt: BigNumberish, anchoredBy: AddressLike}

    export type EvidenceAnchorStructOutput = [caseIdHash: string, documentIdHash: string, contentHash: string, version: bigint, anchoredAt: bigint, anchoredBy: string] & {caseIdHash: string, documentIdHash: string, contentHash: string, version: bigint, anchoredAt: bigint, anchoredBy: string }
  

    export type CustodyAnchorStruct = {caseIdHash: BytesLike, evidenceIdHash: BytesLike, transferIdHash: BytesLike, eventHash: BytesLike, sequence: BigNumberish, anchoredAt: BigNumberish, anchoredBy: AddressLike}

    export type CustodyAnchorStructOutput = [caseIdHash: string, evidenceIdHash: string, transferIdHash: string, eventHash: string, sequence: bigint, anchoredAt: bigint, anchoredBy: string] & {caseIdHash: string, evidenceIdHash: string, transferIdHash: string, eventHash: string, sequence: bigint, anchoredAt: bigint, anchoredBy: string }
  
    }

  export interface EvidenceRegistryInterface extends Interface {
    getFunction(nameOrSignature: "ANCHOR_ROLE" | "DEFAULT_ADMIN_ROLE" | "anchorCustodyEvent" | "anchorEvidence" | "computeAnchorId" | "computeCustodyAnchorId" | "custodyAnchorExistsOnChain" | "exists" | "getAnchor" | "getCustodyAnchor" | "getRoleAdmin" | "grantRole" | "hasRole" | "renounceRole" | "revokeRole" | "supportsInterface" | "verifyAnchor" | "verifyCustodyAnchor"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CustodyEventAnchored" | "EvidenceAnchored" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'ANCHOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'anchorCustodyEvent', values: [BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'anchorEvidence', values: [BytesLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'computeAnchorId', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'computeCustodyAnchorId', values: [BytesLike, BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'custodyAnchorExistsOnChain', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'exists', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getAnchor', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getCustodyAnchor', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyAnchor', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyCustodyAnchor', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'ANCHOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'anchorCustodyEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'anchorEvidence', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeAnchorId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeCustodyAnchorId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'custodyAnchorExistsOnChain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAnchor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCustodyAnchor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyAnchor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyCustodyAnchor', data: BytesLike): Result;
  }

  
    export namespace CustodyEventAnchoredEvent {
      export type InputTuple = [anchorId: BytesLike, caseIdHash: BytesLike, evidenceIdHash: BytesLike, transferIdHash: BytesLike, eventHash: BytesLike, sequence: BigNumberish, anchoredAt: BigNumberish, anchoredBy: AddressLike];
      export type OutputTuple = [anchorId: string, caseIdHash: string, evidenceIdHash: string, transferIdHash: string, eventHash: string, sequence: bigint, anchoredAt: bigint, anchoredBy: string];
      export interface OutputObject {anchorId: string, caseIdHash: string, evidenceIdHash: string, transferIdHash: string, eventHash: string, sequence: bigint, anchoredAt: bigint, anchoredBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EvidenceAnchoredEvent {
      export type InputTuple = [anchorId: BytesLike, caseIdHash: BytesLike, documentIdHash: BytesLike, contentHash: BytesLike, version: BigNumberish, anchoredAt: BigNumberish, anchoredBy: AddressLike];
      export type OutputTuple = [anchorId: string, caseIdHash: string, documentIdHash: string, contentHash: string, version: bigint, anchoredAt: bigint, anchoredBy: string];
      export interface OutputObject {anchorId: string, caseIdHash: string, documentIdHash: string, contentHash: string, version: bigint, anchoredAt: bigint, anchoredBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EvidenceRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): EvidenceRegistry;
    waitForDeployment(): Promise<this>;

    interface: EvidenceRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ANCHOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    anchorCustodyEvent: TypedContractMethod<
      [caseIdHash: BytesLike, evidenceIdHash: BytesLike, transferIdHash: BytesLike, eventHash: BytesLike, sequence: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    anchorEvidence: TypedContractMethod<
      [caseIdHash: BytesLike, documentIdHash: BytesLike, contentHash: BytesLike, version: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    computeAnchorId: TypedContractMethod<
      [caseIdHash: BytesLike, documentIdHash: BytesLike, version: BigNumberish, ],
      [string],
      'view'
    >
    

    
    computeCustodyAnchorId: TypedContractMethod<
      [caseIdHash: BytesLike, evidenceIdHash: BytesLike, transferIdHash: BytesLike, sequence: BigNumberish, ],
      [string],
      'view'
    >
    

    
    custodyAnchorExistsOnChain: TypedContractMethod<
      [anchorId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    exists: TypedContractMethod<
      [anchorId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getAnchor: TypedContractMethod<
      [anchorId: BytesLike, ],
      [[EvidenceRegistry.EvidenceAnchorStructOutput, boolean] & {anchor: EvidenceRegistry.EvidenceAnchorStructOutput, exists: boolean }],
      'view'
    >
    

    
    getCustodyAnchor: TypedContractMethod<
      [anchorId: BytesLike, ],
      [[EvidenceRegistry.CustodyAnchorStructOutput, boolean] & {anchor: EvidenceRegistry.CustodyAnchorStructOutput, exists: boolean }],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    verifyAnchor: TypedContractMethod<
      [anchorId: BytesLike, contentHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    verifyCustodyAnchor: TypedContractMethod<
      [anchorId: BytesLike, eventHash: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ANCHOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'anchorCustodyEvent'): TypedContractMethod<
      [caseIdHash: BytesLike, evidenceIdHash: BytesLike, transferIdHash: BytesLike, eventHash: BytesLike, sequence: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'anchorEvidence'): TypedContractMethod<
      [caseIdHash: BytesLike, documentIdHash: BytesLike, contentHash: BytesLike, version: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'computeAnchorId'): TypedContractMethod<
      [caseIdHash: BytesLike, documentIdHash: BytesLike, version: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'computeCustodyAnchorId'): TypedContractMethod<
      [caseIdHash: BytesLike, evidenceIdHash: BytesLike, transferIdHash: BytesLike, sequence: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'custodyAnchorExistsOnChain'): TypedContractMethod<
      [anchorId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'exists'): TypedContractMethod<
      [anchorId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getAnchor'): TypedContractMethod<
      [anchorId: BytesLike, ],
      [[EvidenceRegistry.EvidenceAnchorStructOutput, boolean] & {anchor: EvidenceRegistry.EvidenceAnchorStructOutput, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getCustodyAnchor'): TypedContractMethod<
      [anchorId: BytesLike, ],
      [[EvidenceRegistry.CustodyAnchorStructOutput, boolean] & {anchor: EvidenceRegistry.CustodyAnchorStructOutput, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verifyAnchor'): TypedContractMethod<
      [anchorId: BytesLike, contentHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verifyCustodyAnchor'): TypedContractMethod<
      [anchorId: BytesLike, eventHash: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'CustodyEventAnchored'): TypedContractEvent<CustodyEventAnchoredEvent.InputTuple, CustodyEventAnchoredEvent.OutputTuple, CustodyEventAnchoredEvent.OutputObject>;
getEvent(key: 'EvidenceAnchored'): TypedContractEvent<EvidenceAnchoredEvent.InputTuple, EvidenceAnchoredEvent.OutputTuple, EvidenceAnchoredEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;

    filters: {
      
      'CustodyEventAnchored(bytes32,bytes32,bytes32,bytes32,bytes32,uint64,uint64,address)': TypedContractEvent<CustodyEventAnchoredEvent.InputTuple, CustodyEventAnchoredEvent.OutputTuple, CustodyEventAnchoredEvent.OutputObject>;
      CustodyEventAnchored: TypedContractEvent<CustodyEventAnchoredEvent.InputTuple, CustodyEventAnchoredEvent.OutputTuple, CustodyEventAnchoredEvent.OutputObject>;
    

      'EvidenceAnchored(bytes32,bytes32,bytes32,bytes32,uint64,uint64,address)': TypedContractEvent<EvidenceAnchoredEvent.InputTuple, EvidenceAnchoredEvent.OutputTuple, EvidenceAnchoredEvent.OutputObject>;
      EvidenceAnchored: TypedContractEvent<EvidenceAnchoredEvent.InputTuple, EvidenceAnchoredEvent.OutputTuple, EvidenceAnchoredEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    
    };
  }