export const PERMISSIONS = {
  CASE_READ: "CASE_READ",
  CASE_UPDATE: "CASE_UPDATE",
  CASE_PARTICIPANT_MANAGE: "CASE_PARTICIPANT_MANAGE",

  DOCUMENT_READ: "DOCUMENT_READ",
  DOCUMENT_UPLOAD: "DOCUMENT_UPLOAD",
  DOCUMENT_UPDATE: "DOCUMENT_UPDATE",
  DOCUMENT_DOWNLOAD: "DOCUMENT_DOWNLOAD",
  DOCUMENT_VERIFY: "DOCUMENT_VERIFY",

  EVIDENCE_CREATE: "EVIDENCE_CREATE",
  EVIDENCE_READ: "EVIDENCE_READ",
  EVIDENCE_UPDATE: "EVIDENCE_UPDATE",

  CUSTODY_TRANSFER: "CUSTODY_TRANSFER",
  CUSTODY_ACCEPT: "CUSTODY_ACCEPT",
  CUSTODY_REJECT: "CUSTODY_REJECT",
  CUSTODY_HISTORY_READ: "CUSTODY_HISTORY_READ",

  AUDIT_READ: "AUDIT_READ",

  CASE_PERMISSION_GRANT: "CASE_PERMISSION_GRANT",
  CASE_PERMISSION_REVOKE: "CASE_PERMISSION_REVOKE"
} as const;

export type PermissionName = typeof PERMISSIONS[keyof typeof PERMISSIONS];
